name: PR Checker
on:
  pull_request:
    branches:
      - main
      - master
jobs:
#  golangci:
#    name: lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/setup-go@v2
#      - uses: actions/checkout@v2
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v2
#
  run-unit-tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: make test